### ISSUE TITLE
Remove complaint_mashpeewampanoag_court.yml?

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-ComplaintMashpeeCourt#1]
There seems to be an old .yml file in the project (`complaint_mashpeewampanoag_court.yml`). If this is no longer being used, you should remove it. My recollection is that doing this in docassemble is not enough on it's own, you will likely also have to remove the file from github directly here: https://github.com/SuffolkLITLab/docassemble-ComplaintMashpeeCourt/blob/main/docassemble/ComplaintMashpeeCourt/data/questions/complaint_mashpeewampanoag_court.yml

**Comment by clmbergin** [comment]
Appears to have been removed already
