### ISSUE TITLE
pro-se guide

### ISSUE THREAD

**Issue by krajusu** [SuffolkLITLab/docassemble-ComplaintMashpeeCourt#6]
add link to the guide
- we want this in the early part of the interview
https://static1.squarespace.com/static/59ca33c0f09ca4a9c58455a9/t/5a3c4a15e2c483c2491735a0/1513900576522/Self-Representation-Guide.-Amended.Jan-2017.pdf

**Comment by clmbergin** [comment]
Added 10/31/24
